=== esustreba/Practice7/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/input"
	xmlns:tns="http://www.example.org/input" elementFormDefault="qualified">
	<xsd:element name="Тourist_vouchers">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Тourist_voucher"
					type="tns:vousher" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="vousher">
		<xsd:sequence>
			<xsd:element name="type" type="tns:type" minOccurs="1" maxOccurs="1" />
			<xsd:element name="Stars" type="tns:Stars"  minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Country" type="tns:country" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Days" type="tns:Days" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Transport" type="tns:Transport" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Rooms" type="tns:Room" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Meals" type="tns:Meals" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Coast" type="tns:Cost" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:simpleType name="type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="weekend"/>
            <xsd:enumeration value="tour"/>
            <xsd:enumeration value="relaxation"/>
            <xsd:enumeration value="pilgrimage"/>
        </xsd:restriction>
    </xsd:simpleType>


	
	<xsd:simpleType name="country">
	<xsd:restriction base="xsd:string">
		<xsd:pattern
			value="([а-яА-ЯёЁ][а-яА-ЯёЁ\s]*)|([A-Za-z][A-Za-z\s]*)" />
	</xsd:restriction>
</xsd:simpleType>
	
	<xsd:simpleType name="Days">
	<xsd:restriction base="xsd:nonNegativeInteger">
		<xsd:minExclusive value="2" />
		<xsd:maxExclusive value="14" />
	</xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="Transport">
	<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Rail"/>
            <xsd:enumeration value="Plane"/>
            <xsd:enumeration value="Auto"/>
            <xsd:enumeration value="Ship"/>
		</xsd:restriction>
</xsd:simpleType>


	<xsd:simpleType name="Stars">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:minExclusive value="0" />
			<xsd:maxExclusive value="6" />
		</xsd:restriction>
	</xsd:simpleType>
	
		<xsd:simpleType name="Room">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Standart"/>
            <xsd:enumeration value="Suite"/>
            <xsd:enumeration value="Lux"/>
            <xsd:enumeration value="Villa"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	   <xsd:simpleType name="Meals">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="OB"/>
            <xsd:enumeration value="HB"/>
            <xsd:enumeration value="AI"/>
            
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:complexType name="Cost">
     <xsd:simpleContent>
            <xsd:extension base="xsd:decimal">
                <xsd:attribute name="Currency" type="tns:currency" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>   
    </xsd:complexType>
    
    <xsd:simpleType name="currency">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="EUR"/>
            <xsd:enumeration value="USD"/>
            <xsd:enumeration value="UAH"/>
            <xsd:enumeration value="RUB"/>
        </xsd:restriction>
    </xsd:simpleType>


	

</xsd:schema>

=== esustreba/Practice7/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Тourist_vouchers xmlns:tns="http://www.example.org/input" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/input input.xsd ">
  <tns:Тourist_voucher>
    <tns:type>tour</tns:type>
    <tns:Stars>3</tns:Stars>
    <tns:Country>USA</tns:Country>
    <tns:Days>7</tns:Days>
    <tns:Transport>Plane</tns:Transport>
    <tns:Rooms>Standart</tns:Rooms>
    <tns:Meals>OB</tns:Meals>
    <tns:Coast Currency="USD">2700.0</tns:Coast>
  </tns:Тourist_voucher>
  
    <tns:Тourist_voucher>
    <tns:type>tour</tns:type>
    <tns:Stars>5</tns:Stars>
    <tns:Country>Egypt</tns:Country>
    <tns:Days>12</tns:Days>
    <tns:Transport>Plane</tns:Transport>
    <tns:Rooms>Lux</tns:Rooms>
    <tns:Meals>AI+</tns:Meals>
    <tns:Coast Currency="USD">1700.0</tns:Coast>
  </tns:Тourist_voucher>
  
    <tns:Тourist_voucher>
    <tns:type>weekend</tns:type>
    <tns:Stars>3</tns:Stars>
    <tns:Country>Czech</tns:Country>
    <tns:Days>3</tns:Days>
    <tns:Transport>Auto</tns:Transport>
    <tns:Rooms>Standart</tns:Rooms>
    <tns:Meals>HB</tns:Meals>
    <tns:Coast Currency="EUR">900.0</tns:Coast>
  </tns:Тourist_voucher>
</tns:Тourist_vouchers>
